# Generated by Django 5.0.7 on 2024-08-05 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misto', models.CharField(max_length=50, verbose_name='Name')),
                ('gruz', models.CharField(max_length=50, verbose_name='Description')),
                ('litres', models.CharField(max_length=5, verbose_name='Litres')),
                ('price', models.CharField(max_length=25, verbose_name='Price')),
                ('massa', models.CharField(max_length=50, verbose_name='Massa')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ваши данные',
            },
        ),
    ]
