# Generated by Django 5.0.7 on 2024-08-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='gruz',
            field=models.CharField(choices=[('corn', 'Кукурудза'), ('wheat', 'Пшениця')], max_length=10, verbose_name='Description'),
        ),
    ]
