# Generated by Django 5.0.7 on 2024-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_task_gruz'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='punkt',
            field=models.CharField(default='', max_length=50, verbose_name='Punkt'),
            preserve_default=False,
        ),
    ]
