# Generated by Django 5.0.7 on 2024-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_task_options_task_derzh_nomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='derzh_nomer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='derzh_nomer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='litres',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Litres'),
        ),
        migrations.AlterField(
            model_name='task',
            name='massa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Massa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='misto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='odometr_viezd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='odometr_viezd'),
        ),
        migrations.AlterField(
            model_name='task',
            name='odometr_vizd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='odometr_vizd'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='task',
            name='punkt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Punkt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='skilki_vantazhu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='skilki_vantazhu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ttn_nomer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ttn_nomer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='zaprawka_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='zaprawka_time'),
        ),
    ]
