# Generated by Django 5.0.7 on 2024-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_task_derzh_nomer_alter_task_litres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='gruz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
    ]
